#!/bin/bash
PSQL="psql -U vocabulink vocabulink"

echo "SELECT COUNT(*) AS \"# of members\" FROM member" | $PSQL
echo "SELECT COUNT(*) AS \"# of links\" FROM link WHERE NOT deleted" | $PSQL
echo "SELECT COUNT(*) AS \"# of linkword stories\" FROM linkword_story INNER JOIN link USING (link_no) WHERE NOT deleted" | $PSQL
echo "SELECT COUNT(*) AS \"# of linkwords\" FROM link_linkword ll INNER JOIN link l ON (l.link_no = ll.link_no AND NOT deleted)" | $PSQL
echo "SELECT COUNT(*) AS \"# of soundalikes\" FROM link_soundalike ls INNER JOIN link l ON (l.link_no = ls.link_no AND NOT deleted)" | $PSQL
echo "SELECT COUNT(*) AS \"# of links in review\" FROM link_to_review" | $PSQL
echo "SELECT COUNT(*) AS \"# of reviews\" FROM link_review" | $PSQL
echo "SELECT COUNT(*) AS \"# of my reviews\" FROM link_review WHERE member_no = 1" | $PSQL

echo "Top 10 reviewers this week"
echo "SELECT username, COUNT(*) AS reviews FROM link_review INNER JOIN member USING (member_no) WHERE actual_time BETWEEN '$(date --date="1 week ago")' AND NOW() GROUP BY username ORDER BY reviews DESC LIMIT 10" | $PSQL

echo "Top 10 reviewers of all time"
echo "SELECT username, COUNT(*) AS reviews FROM link_review INNER JOIN member USING (member_no) GROUP BY username ORDER BY reviews DESC LIMIT 10" | $PSQL

echo "Active reviewers in the last week"
echo "SELECT COUNT(DISTINCT(member_no)) FROM link_review WHERE actual_time BETWEEN NOW() - INTERVAL '1 WEEK' AND NOW();" | $PSQL

echo "Active reviewers in the last month"
echo "SELECT COUNT(DISTINCT(member_no)) FROM link_review WHERE actual_time BETWEEN NOW() - INTERVAL '1 MONTH' AND NOW();" | $PSQL
