(add-to-list 'load-path "~/.emacs.d/muse-3.12/lisp")
(require 'muse-mode)
(require 'muse-html)
(setq muse-xhtml-style-sheet "")
(setq muse-xhtml-header "\n<h1><lisp>(muse-publishing-directive \"title\")</lisp></h1>\n<h2><lisp>(muse-publishing-directive \"author\")</lisp></h2>\n")
(setq muse-xhtml-footer "")